Repository osuAkatsuki/bancho-service, pull requests merged in 2023-10, with the labels that each got.

#52 async/await with tornado
  common/db/dbConnector.py
  common/web/cheesegull.py
  common/web/requestsManager.py
  events/loginEvent.py
  handlers/apiFokabotMessageHandler.py
  handlers/apiIsOnlineHandler.py
  handlers/apiOnlineUsersHandler.py
  handlers/apiServerStatusHandler.py
  handlers/apiVerifiedStatusHandler.py
  handlers/ciTriggerHandler.py
  handlers/mainHandler.py
  main.py
  objects/glob.py
  requirements.txt
Labels: code quality, performance

#55 refactor http to async/await
  .env.example
  common/log/logUtils.py
  common/ripple/userUtils.py
  common/web/cheesegull.py
  common/web/discord.py
  constants/fokabotCommands.py
  events/changeMatchPasswordEvent.py
  events/loginEvent.py
  events/logoutEvent.py
  events/matchFramesEvent.py
  events/matchLockEvent.py
  events/partLobbyEvent.py
  events/spectateFramesEvent.py
  events/userStatsRequestEvent.py
  handlers/apiIsOnlineHandler.py
  handlers/apiOnlineUsersHandler.py
  helpers/chatHelper.py
  helpers/systemHelper.py
  irc/ircserver.py
  main.py
  objects/glob.py
  objects/match.py
  objects/osuToken.py
  objects/tokenList.py
  pubSubHandlers/updateStatsHandler.py
  requirements.txt
  settings.py
Labels: code quality, performance

#50 Graceful application shutdown
  .env.example
  common/redis/generalPubSubHandler.py
  helpers/systemHelper.py
  irc/ircserver.py
  main.py
  settings.py
Labels: bug, code quality

#59 Refactor logs to structured objects
  .gitignore
  .pre-commit-config.yaml
  common/generalUtils.py
  common/log/logUtils.py
  common/log/rap_logs.py
  common/redis/generalPubSubHandler.py
  common/redis/pubSub.py
  common/ripple/userUtils.py
  common/web/discord.py
  constants/fokabotCommands.py
  events/cantSpectateEvent.py
  events/changeProtocolVersionEvent.py
  events/createMatchEvent.py
  events/joinMatchEvent.py
  events/loginEvent.py
  events/logoutEvent.py
  events/spectateFramesEvent.py
  events/startSpectatingEvent.py
  events/stopSpectatingEvent.py
  events/userPanelRequestEvent.py
  events/userStatsRequestEvent.py
  handlers/ciTriggerHandler.py
  helpers/chatHelper.py
  helpers/consoleHelper.py
  helpers/locationHelper.py
  helpers/systemHelper.py
  irc/ircserver.py
  logging.yaml.example
  main.py
  objects/channelList.py
  objects/match.py
  objects/osuToken.py
  objects/tokenList.py
  pubSubHandlers/changeUsernameHandler.py
  requirements.txt
Labels: enhancement, code quality

#48 more flexibility for lock api
  objects/redisLock.py
Labels: enhancement, code quality

#63 Remove some dead code
  .env.example
  .git-blame-ignore-revs
  common/channel_utils.py
  common/constants/bcolors.py
  common/constants/osuFlags.py
  common/ddog/__init__.py
  common/ddog/datadogClient.py
  common/generalUtils.py
  common/log/rap_logs.py
  common/ripple/passwordUtils.py
  common/ripple/scoreUtils.py
  common/ripple/userUtils.py
  constants/exceptions.py
  constants/packetIDs.py
  constants/serverPackets.py
  helpers/cryptHelper.py
  helpers/packetHelper.py
  main.py
  objects/glob.py
  objects/match.py
  requirements-dev.txt
  requirements.txt
  settings.py
Labels: code quality/maintainability

#66 Dockerize bancho-service & pull secrets from vault
  .dockerignore
  .env.example
  Dockerfile
  Makefile
  scripts/await-service.sh
  scripts/bootstrap.sh
  scripts/run-service.sh
  settings.py
Labels: enhancement

#70 Deploy to production from CI
  .github/workflows/production-deploy.yml
Labels: enhancement

#73 Split jobs into separate app components
  .env.example
  common/ripple/userUtils.py
  constants/exceptions.py
  constants/fokabotCommands.py
  lifecycle.py
  main.py
  objects/osuToken.py
  objects/tokenList.py
  scripts/bootstrap.sh
  scripts/run-api.sh
  scripts/run-consume-pubsub-events.sh
  scripts/run-reset-all-tokens-spam-rate.sh
  scripts/run-timeout-inactive-tokens.sh
  settings.py
  workers/crons/reset_all_tokens_spam_rate.py
  workers/crons/timeout_inactive_tokens.py
  workers/daemons/consume_pubsub_events.py
Labels: bug, code quality/maintainability

#71 More logging, embed reformat & added reason requirement to some commands 💥
  common/log/rap_logs.py
  constants/fokabotCommands.py
Labels: enhancement, code quality/maintainability

#82 Rename instances of "fokabot" to "chatbot"
  constants/chatbotCommands.py
  events/setAwayMessageEvent.py
  handlers/apiChatbotMessageHandler.py
  helpers/chatHelper.py
  main.py
  objects/channelList.py
  objects/chatbot.py
Labels: code quality/maintainability

#84 Allow deploy from feature branches & add log for missing stats on getUserStats
  .github/workflows/production-deploy.yml
  common/ripple/userUtils.py
  objects/osuToken.py
Labels: enhancement

#85 Hook exception handlers & format to logs correctly
  common/exception_handling.py
  main.py
  workers/crons/reset_all_tokens_spam_rate.py
  workers/crons/timeout_inactive_tokens.py
  workers/daemons/consume_pubsub_events.py
Labels: enhancement
