Repository osuAkatsuki/bancho-service, pull requests merged in 2024-07, with the labels that each got.

#169 Remove the concept of "match frames" for tracking score submission match details
  events/matchCompleteEvent.py
  events/matchFramesEvent.py
  objects/match.py
  objects/matchList.py
Labels: performance

#172 rewrite changeAction event to broadcast to main stream
  events/changeActionEvent.py
Labels: sustainability, performance

#173 channel smembers optimizations
  helpers/chatHelper.py
  objects/channelList.py
  objects/match.py
Labels: performance

#171 Multiplayer game start optimization
  objects/match.py
Labels: performance

#179 Add !addbn command
  constants/chatbotCommands.py
Labels: enhancement

#145 osu! speedruns concept poc
  common/speedrunning.py
  constants/chatbotCommands.py
Labels: enhancement
