Repository osuAkatsuki/bancho-service, pull requests merged in 2024-05, with the labels that each got.

#126 Refactor user utils to have better naming, descriptions, and use snake_case. Remove IP-Session associations & auth bypass. Remove unused systems.
  common/log/audit_logs.py
  common/ripple/userUtils.py
  constants/chatbotCommands.py
  constants/serverPackets.py
  events/changeActionEvent.py
  events/friendAddEvent.py
  events/friendRemoveEvent.py
  events/loginEvent.py
  handlers/apiIsOnlineHandler.py
  helpers/chatHelper.py
  irc/ircserver.py
  objects/chatbot.py
  objects/osuToken.py
  objects/tokenList.py
  pubSubHandlers/banHandler.py
  pubSubHandlers/changeUsernameHandler.py
  pubSubHandlers/unbanHandler.py
  pubSubHandlers/wipeHandler.py
Labels: code quality/maintainability

#113 Refactor helpers/chatHelper.py and related modules
  .env.example
  constants/__init__.py
  constants/chatbotCommands.py
  constants/serverPackets.py
  events/loginEvent.py
  events/setAwayMessageEvent.py
  events/spectateFramesEvent.py
  handlers/apiChatbotMessageHandler.py
  helpers/chatHelper.py
  main.py
  objects/banchoConfig.py
  objects/channelList.py
  objects/chatbot.py
  objects/glob.py
  objects/match.py
  objects/osuToken.py
  objects/stream.py
  objects/streamList.py
  settings.py
Labels: code quality/maintainability

#130 Fix all type errors, improve token fetch perf, async geoloc fetch on login, refactor poor quality
  .github/workflows/lint.yml
  .github/workflows/production-deploy.yml
  adapters/__init__.py
  common/generalUtils.py
  common/log/logger.py
  common/redis/generalPubSubHandler.py
  common/redis/pubSub.py
  common/redis/pubsubs.py
  common/ripple/scoreUtils.py
  common/ripple/user_utils.py
  common/web/discord.py
  common/web/requestsManager.py
  constants/chatbotCommands.py
  constants/serverPackets.py
  events/createMatchEvent.py
  events/joinMatchEvent.py
  events/loginEvent.py
  events/logoutEvent.py
  events/partMatchEvent.py
  events/startSpectatingEvent.py
  handlers/apiChatbotMessageHandler.py
  handlers/apiIsOnlineHandler.py
  helpers/chatHelper.py
  helpers/countryHelper.py
  helpers/locationHelper.py
  helpers/packetHelper.py
  helpers/systemHelper.py
  main.py
  objects/banchoConfig.py
  objects/channelList.py
  objects/chatbot.py
  objects/dbPool.py
  objects/glob.py
  objects/match.py
  objects/matchList.py
  objects/osuToken.py
  objects/slot.py
  objects/tokenList.py
  pubSubHandlers/banHandler.py
  pubSubHandlers/changeUsernameHandler.py
  pubSubHandlers/disconnectHandler.py
  pubSubHandlers/notificationHandler.py
  pubSubHandlers/unbanHandler.py
  pubSubHandlers/updateSilenceHandler.py
  pubSubHandlers/updateStatsHandler.py
  pubSubHandlers/wipeHandler.py
  requirements-dev.txt
  workers/daemons/consume_pubsub_events.py
Labels: code quality/maintainability, performance

#131 Upgrade to python3.11
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Dockerfile
  common/exception_handling.py
  common/log/audit_logs.py
  common/log/logger.py
  common/ripple/scoreUtils.py
  common/ripple/user_utils.py
  common/web/requestsManager.py
  constants/chatbotCommands.py
  constants/serverPackets.py
  events/logoutEvent.py
  handlers/mainHandler.py
  helpers/chatHelper.py
  main.py
  objects/channelList.py
  objects/chatbot.py
  objects/dbPool.py
  objects/glob.py
  objects/match.py
  objects/matchList.py
  objects/osuToken.py
  objects/redisLock.py
  objects/slot.py
  objects/tokenList.py
  pubSubHandlers/changeUsernameHandler.py
Labels: sustainability

#135 Require kwargs for non-PK fields in partial_update APIs
  objects/match.py
  objects/osuToken.py
  objects/slot.py
Labels: sustainability

#133 Use redis pipelines for atomic multi-operations; refactor some code at login
  common/ripple/user_utils.py
  constants/chatbotCommands.py
  constants/serverPackets.py
  events/loginEvent.py
  objects/channelList.py
  objects/match.py
  objects/osuToken.py
  objects/tokenList.py
Labels: bug, sustainability

#138 Amplitude event for chatbot command invocation & cleanup the chatbot.query() API
  helpers/chatHelper.py
  objects/chatbot.py
Labels: enhancement, sustainability

#139 Remove unused or unvaluable commands/code, some minor rewrites
  constants/chatbotCommands.py
  constants/exceptions.py
  events/loginEvent.py
  handlers/apiServerStatusHandler.py
  helpers/systemHelper.py
  objects/glob.py
  objects/match.py
  objects/osuToken.py
Labels: sustainability

#140 Track last /np in public channels
  constants/chatbotCommands.py
Labels: enhancement
